### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by nebulon42** [hsluv/hsluv#33]
I think that is not a very good move as it poses problems for downstream projects. I have added support for husl to downstream projects https://github.com/mapbox/carto and https://github.com/omniscale/magnacarto. There you can specify the colours with husl(...). Now I have to rename that, which requires a major version increase.

At least some communication up-front would have been good, also about the reasons for renaming. I'm now thinking of dropping support again altogether as I'm missing the necessary stability.

**Comment by boronine** [comment]
You are right that I should have communicated the move upfront, I apologize for the annoyance. I will post some suggestions under the carto issue you created.

The reason for the change is that HSLuv is a name that is consistent with the naming conventions of colorimetry. I confirmed this idea with two experts, so I feel confident about the name now. I think it's going to have a positive long-term effect on the project's credibility.

**Comment by williammalo** [comment]
I updated the glsl port to the new name
Here's the new repo: https://github.com/williammalo/hsluv-glsl

**Comment by boronine** [comment]
@williammalo excellent, thank you! I updated the link on the Implementations page.
