### ISSUE TITLE
Color picker text fields are unreadable due to excess padding

### ISSUE THREAD

**Issue by roryokane** [hsluv/hsluv#34]
When I view http://www.hsluv.org/ in Firefox, the text in each color picker text field is unreadable because its edges are cut off:

![text fields with broken padding](https://cloud.githubusercontent.com/assets/79168/21269367/7aa37e5a-c380-11e6-858e-49c9737ffacd.png)

The browser inspector tells me that this is caused by this CSS rule from [`min.min.css`][min.min.css], which applies to those `<input>`s:

```css
textarea, input, select {
  padding: 8px;
  border: 1px solid #ccc;
}
```

When I disable the `padding` rule using the inspector, the text fields are fixed:

![text fields with fixed padding](https://cloud.githubusercontent.com/assets/79168/21269388/87c58b0a-c380-11e6-8d19-7c570522d1b3.png)

It’s not obvious to me how to fix the problem, because [`website/static/css/main.css`][main.css] contains no such `padding` rule.

[main.css]: https://github.com/hsluv/hsluv/blob/e6979a0a08a0216f9f19da7d83bbfaab2a0fa033/website/static/css/main.css
[min.min.css]: https://github.com/hsluv/hsluv/blob/e6979a0a08a0216f9f19da7d83bbfaab2a0fa033/website/static/css/min.min.css

**Comment by boronine** [comment]
Thanks for the catch!
