### ISSUE TITLE
vertically flip plots in the comparison page

### ISSUE THREAD

**Issue by waldyrious** [hsluv/hsluv#35]
In http://www.hsluv.org/comparison/, the HSL and CIELAB LCh representations seem to be plotted with a reversed Y axis compared to the HSLuv and HPLuv plots. Either the first two need to be flipped, or the latter two, or the difference needs to be acknowledged and explained in the text of that page.

**Comment by boronine** [comment]
Thanks for the report!

**Comment by waldyrious** [comment]
Thanks for the quick fix! :) When can we expect this to be on the live website?

**Comment by boronine** [comment]
It should be live now! Actually, I deployed it immediately. It was probably cached in your browser.

**Comment by waldyrious** [comment]
Oh, makes sense :) in any case, I can now see the updated version, thanks!
