### ISSUE TITLE
Haxe→JS : Sys is unavailable

### ISSUE THREAD

**Issue by Eiyeron** [hsluv/hsluv#36]
I saw in `RunTests` and `Snapshot` that they use `Sys` which [isn't](http://api.haxe.org/Sys.html) on javascript, thus `Sys.exit` and `Sys.stdout` doesn't work at all.

Maybe adding a compile-time define to use alternatives or JS could make work, like using `js.Browser.console.log` on browsers and its equivalent on Node.JS.

**Comment by boronine** [comment]
Thanks for the report!
