### ISSUE TITLE
Separate exports for each function

### ISSUE THREAD

**Issue by asilvas** [hsluv/hsluv#38]
This sort of export is bad practice for browser-based consumers:

```
var root = {
    "hsluvToRgb": hsluv.Hsluv.hsluvToRgb,
    "rgbToHsluv": hsluv.Hsluv.rgbToHsluv,
    "hpluvToRgb": hsluv.Hsluv.hpluvToRgb,
    "rgbToHpluv": hsluv.Hsluv.rgbToHpluv,
    "hsluvToHex": hsluv.Hsluv.hsluvToHex,
    "hexToHsluv": hsluv.Hsluv.hexToHsluv,
    "hpluvToHex": hsluv.Hsluv.hpluvToHex,
    "hexToHpluv": hsluv.Hsluv.hexToHpluv
};
```

Would help browser-based solutions by allowing us to only import the functions we require, ala `require('hsluv/rgbToHsluv')`. 

Great work!

**Comment by boronine** [comment]
Thanks Aaron! I assume the motivation here is to make the compiled JS file smaller? In that case it's probably not worth it since the benefit would be small (minified HSLuv is only about 4240 bytes) and the cost large (hsluv.js is generated from Haxe, so splitting it up is not trivial).

**Comment by asilvas** [comment]
Correct. 4KB isn't horrible, but it isn't small either. An app is often made up of many libraries. But I understand if it isn't trivial..

**Comment by boronine** [comment]
I'm going to close this. I'll consider it again if someone else complains about it.
