### ISSUE TITLE
RGB to HSLuv and back to RGB is not consistent.

### ISSUE THREAD

**Issue by AeonFr** [hsluv/hsluv#43]
I'm trying to convert an RGB color to HSLuv and then turn it back into RGB.

the color in question is rgb(0,167,135)

When converting back from Hsluv to RGB, the value for "RED" is not consistent, in fact is kind of weird because it contains letters.... I'm getting `-9.431233571888242e-14`

This is the code Being executed

```
<script src="/public/js/hsluv.min.js"></script>
  <script type="text/javascript">

    var percentageFrom255 = p255 = function(num){
      return num/255
    }

    var  green = [0,p255(167),p255(135)];
// this is equivalent to [0, 0.6549019607843137, 0.5294117647058824]

    var  greenHsluv = hsluv.rgbToHsluv(green);

    console.log('green is: ', green, ' & in HSLUV: ', greenHsluv, ' & back in RGB: ', hsluv.hsluvToRgb(greenHsluv) );
/* this outputs:
green is:  (3) [0, 0.6549019607843137, 0.5294117647058824] 
& in HSLUV:  (3) [162.74543122553402, 99.99999999999123, 61.1201850735859] 
& back in RGB:  (3) [-9.431233571888242e-14, 0.6549019607843142, 0.5294117647058815]
*/
  </script>
```

All the other values (for Green and Blue) match almost exactly, and I've tried with a different color and everything works as expected. It's just for this color I'm not getting right the Red hue (witch should return `0`)

**Comment by mity** [comment]
Computers are unable to use real numbers with absolute precision. So all computations using the types `float` or `double` are subject for rounding errors. That is especially close when dealing e.g. with very small numbers (close to zero).

Furthermore the output with letters you see is so called [scientific notation](https://en.wikipedia.org/wiki/Scientific_notation). So `-9.431233571888242e-14` is actually `-0.00000000000009431233571888242`. So you see it is pretty close to the zero you expect.

**Comment by AeonFr** [comment]
Oh I'm sorry, I was suspecting this was in scientific notation but I was just expecting a 0 and I thought the output was a negative number. Actually I don't remember much about the scientific notation from high school, probably I should have done more research before submitting this issue. Anyway, thanks for that explanation 😃

The output was correct, simply not in the format I was expecting. I'm closing this issue.
