### ISSUE TITLE
Haskell port candidate

### ISSUE THREAD

**Issue by modalduality** [hsluv/hsluv#45]
Hi,
I recently completed the Haskell port.

The candidate (not official/finalized yet) release is on Hackage at https://hackage.haskell.org/package/hsluv-haskell-0.1.0.0/candidate.

Source is at https://git.modalduality.org/hsluv-haskell/tree/.

What else needs to be done (other than finalizing the Hackage release)?

**Comment by boronine** [comment]
Excellent! The only issue that comes to mind is the lack of separation between the public and private APIs. I'm not sure if Haskell provides a convention for this. Do as you see fit.

Other than that, just let me know when you finalize the release and I'll add a link in the Implementations page: https://github.com/hsluv/hsluv/commit/ce3fc4ee24259d9475915c245358d92267544a62

I can also add a link in the Credits page. Let me know which page I should link to and whether to call you @modalduality or something else.

Looking forward to adding Haskell to our list :)

**Comment by modalduality** [comment]
Ah, good catch. The `HSLuv` module doesn't export the constants or utility functions now.

Just released it, too: https://hackage.haskell.org/package/hsluv-haskell-0.1.0.0.

Please link to https://modalduality.org. `modal/duality` is good. Thanks!

**Comment by boronine** [comment]
Done and done. Thanks again!

**Comment by modalduality** [comment]
Thanks. Just one note, I'm not sure how Hackage works exactlybut you may want to remove the "-0.1.0.0" from the end of that URL, in case it displays an older version even if another is uploaded.

Thanks again. I had no idea what perceptually uniform colorspaces were and was very confused when my gradient code would display seven greens in a row, HSLuv solves my problem :)

**Comment by boronine** [comment]
Good catch, fixed! I'm glad you found HSLuv useful :)
