### ISSUE TITLE
Could we add more functions to the public javascript api?

### ISSUE THREAD

**Issue by chrisgervang** [hsluv/hsluv#46]
At the moment, the `hsluv` javascript package publishes with many functions that aren't exposed  publicly (they are already present in the compiled file, but left out of the [export file](https://github.com/hsluv/hsluv/blob/master/javascript/api-public.js)). 

I would like to expose these  so that I can update the `color-space` npm library from `husl` to `hsluv`.

Functions:
**hsluvToLch**, **lchToHsluv**

**hpluvToLch**, **lchToHpluv**

**rgbToXyz**, **xyzToRgb**

**rgbToLch**, **lchToRgb**

**luvToXyz**, **xyzToLuv**

**lchToLuv**, **luvToLch**

**Comment by boronine** [comment]
I'm good with the change. Thanks for the PR!
