### ISSUE TITLE
Improve precision & smoothness of hsluv/website/picker.js?

### ISSUE THREAD

**Issue by no-identd** [hsluv/hsluv#49]
At the moment the sliders seem to lose a lot of precision needlessly, which results in an accuracy loss. If I set the saturation to 100, the lightness to 50, and move the hue slider to 73.4 (#887700) and I hold the left mouse button and move my mouse ONE PIXEL to the right, the next value becomes 75.7 (#867800).

A VERY brief glance over the code didn't make me sure where this comes about, so I'll just speculate and assume that this comes about due to either:
* some snapping to the closest /possible/ 8*3 bit RGB value (seeing how this resulted in an increase by 1 on the green channel, this seems plausible. But I already get that if I plug in ); or
* using floor for number aesthetics (but really, please don't do this. Really bad UX actually.); or
* using ints where one ought to use floats

Either of these seems problematic.

Also, if you want to go really crazy, redo the picker so it does what Adobe does here:

https://color.adobe.com/create/color-wheel/

 but in HSLuv.

**Comment by MeksPwnschlager** [comment]
Want!

**Comment by no-identd** [comment]
Update:
In fact, it seems like the case appears even worse, the sliders seem to exhibit some weird DPI dependency? The values it snaps to and the 'snap range' seems to change depending on the zoom level of the browser...

**Comment by boronine** [comment]
@no-identd the behavior you're seeing can be explained more simply.

Moving the slider by 1 pixel will change the hue value by 360 / slider width (px) = 360 / 161 = 2.236. The reason it appears as "snapping" is that mouse events have a pixel-level precision, so we cannot detect a subpixel mouse move. Apparently Chrome is supposed to support subpixel precision [1], but at least on my machine it doesn't (MacOS 10.13, Chrome 64). In either case, picker.js treats mouse coordinates as doubles so the code is ready as soon as support is rolled out.

I could not reproduce the issue with zooming on my machine. Could you give me specific values you are seeing as well as the browser you are using?

It seems that the general issue here can be mitigated by making the sliders wider, which would involve a slight redesign of the picker layout.

(btw, I'd love to see an HSLuv picker similar to the Adobe color wheel, but won't have time to work on it myself)

[1] https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/clientX#Browser_compatibility

**Comment by no-identd** [comment]
I had a lengthy reply to this typed out, unfortunately it died. What it boiled down:
Independent of the subpixel precision issue, changing the slider width to 180 should improve matters greatly without messing up the website design.

**Comment by boronine** [comment]
This should do it: http://www.hsluv.org/
