### ISSUE TITLE
Dedicated JS implementation

### ISSUE THREAD

**Issue by cangoektas** [hsluv/hsluv#51]
Hey @boronine and team,

what is your opinion on having a dedicated JS implementation instead of generating code from Haxe? At the top of my head, I can think of the following reasons:

- easier to collaborate (huge JS community)
- easier support for JavaScript specific syntax (was thinking about supporting `func([a,b,c])` and `func(a,b,c)`)
  - maybe possible with Haxe too?
- richer tooling/easier to maintain than `nix` and `makeNodePackage`?
  - easier support exporting other formats like unminified UMD, and ESM

I'm not familiar with Haxe so please correct me if you disagree with any of these points. I would also volunteer to work on the JS implementation if there are enough votes for it.

**Comment by boronine** [comment]
Hey @cangoektas,

There's pros and cons to our approach here. You definitely have more freedom in a dedicated repository. The benefit of our approach is to be able to make a change in a single code base and instantly release it to multiple languages. I am maintaining many of them now, and I have parts of it automated with Haxe and nix. [I wrote about it here](http://www.boronine.com/2018/02/02/Nix/).

I think a dedicated JS implementation is fine as long as someone is dedicated to keep it reasonably maintained. The spec hasn't changed in a long time.

And thank you for your interest in the project. I appreciate it and welcome these kind of ideas. I'm sure something interesting can be done with it.

**Comment by cangoektas** [comment]
Thanks for being so open to the idea and for the link to the blog post! Reading through it I definitely see the advantages. It seems really powerful to reuse a single codebase. Less code to maintain, being able to ship fixes instantly to multiple languages, etc. The only "problem" I had was not being able to read the JavaScript implementation and contributing to it.

I think I'd definitely like to try to work on it and see what kind of improvements can be made. I have a feeling that a dedicated JS implementation could really help HSLuv but maybe I'll first try and see how far I can get and then we can still decide if we'd like to switch or keep the current generated code. Does that sound good to you? :)

**Comment by boronine** [comment]
Of course, sounds great!
