### ISSUE TITLE
Problem with C code on Arduino?

### ISSUE THREAD

**Issue by ElbyMann** [hsluv/hsluv#55]
I'm trying to get the C version running on an Arduino.  I've made a couple of small tweaks to get code to compile: removing the C++ includes in the header file, and changing the name of the "round" function to "roundHsluv" to avoid name conflict.  The following test program:

#include "husl.h"

void setup() {
  float r, g, b;
  Serial.begin(9600);
  
  HUSLtoRGB(&r, &g, &b, 0.0, 100.0, 50.0);
  int red = 255*r;
  int green = 255*g;
  int blue = 255*b;
  
  Serial.print(F("   red: "));
  Serial.print(red);
  Serial.print(F(" green: "));
  Serial.print(green);
  Serial.print(F(" blue: "));
  Serial.println(blue);
}

Produces the output:      red: 233 green: 0 blue: 100,  however, I expect the output to be red: 255 green: 0 blue: 0

I'm wondering if the problem is 16-bit integers on the Arduino?   Can someone help me get this up-and-running?  Thanks.

**Comment by mity** [comment]
I have no experience with Arduino. What exactly do you call "the C version"? It seems as something very legacy. The project has been renamed to HSLuv years ago. Can't you use <https://github.com/hsluv/hsluv-c>?

**Comment by ElbyMann** [comment]
The downside of Google is that legacy code is often the result.  Thanks
very much for the pointer to more up-to-date code!
