### ISSUE TITLE
Surprising index upper bound

### ISSUE THREAD

**Issue by StoneCypher** [hsluv/hsluv#56]
[On this line I find myself confused](https://github.com/hsluv/hsluv/blob/master/haxe/src/hsluv/Hsluv.hx#L63)

```haxe
        for (c in 0...3) {
            var m1:Float = m[c][0];
```

`m` is an array with three rows.  Why is that range four positions?

On [porting to typescript]() I had to change this bound to 2.  I can't tell if this is a bug that `haxe` is being graceful about, or if I'm just missing something and about to look dumb

**Comment by mity** [comment]
I have never used Haxe, but according to [the docs](https://haxe.org/manual/expression-for.html#range-iteration), the min value of the range is inclusive but the maximal value is exclusive.

I.e. the given `for` loop should be equivalent to `for (c = 0; c < 3; c++)` in C so it should iterate over three values (0, 1 and 2).

**Comment by boronine** [comment]
Closing this issue. Welcome to HSLuv, @StoneCypher, let us know if you find anything else :)
