### ISSUE TITLE
Extremely small numeric drift against tests

### ISSUE THREAD

**Issue by StoneCypher** [hsluv/hsluv#58]
I'm attempting to [port to typescript](https://github.com/StoneCypher/hsluv-ts).

In running your tests, I am seeing *extremely* small numeric drift (usually on the order of 10<sup>-15</sup> or smaller.)

![image](https://user-images.githubusercontent.com/77482/74621140-91665f80-50f0-11ea-843f-c876cb67d6d3.png)

I haven't really dug around, but I suspect that Typescript is juggling the math in a way that screws with IEEE numeric precision's edges.

Are deviations that small considered acceptable?

**Comment by StoneCypher** [comment]
I mean, my grandchildren will never have a monitor that can show colors that fine, nor will the aliens who murder them have eyes that can see it

Someone ask a mantis shrimp what they think?

**Comment by leeoniya** [comment]
@StoneCypher

if you're interested, i did a memory-efficient port of the C impl to JS. i have not run tests against it, but it seems to work well. i can publish it.

**Comment by boronine** [comment]
In the context of this project, this is a totally acceptable error. I believe the error tolerances are already slightly different in different HSLuv implementations due to various quirks. Increase the tolerance as much as you need to get the tests to pass, the tests will still be useful to find regressions when you do later changes.

@leeoniya I encourage you to publish your port. I would not advertise it on the implementations page [1] at this point but I would link to it from the JavaScript package README [2] for people who are looking for extra performance.

[1] https://www.hsluv.org/implementations/
[2] https://www.npmjs.com/package/hsluv

**Comment by StoneCypher** [comment]
> Increase the tolerance as much as you need to get the tests to pass, 

Understood, and appreciated.  I believe that this is generally the correct approach.

For the sake of interesting trivia, these appear to fall off two's logarithmically, and as I removed zeros, violations finally stopped at a tolerance of `0.000 000 000 1`

**Comment by StoneCypher** [comment]
@leeoniya - I'd like to see it for the sake of it being interesting, but my actual goal here is to get this to be easy under ts/rollup

**Comment by boronine** [comment]
@StoneCypher have you tried hsluv 0.1.0 that comes with type definitions? Did you have any issues with it under your setup?

**Comment by StoneCypher** [comment]
I didn't even see them.  They're supposed to be in root.  It didn't occur to me that your project root would be something other than the repo root.  I haven't seen that in years

I tried installing, my tooling didn't pick 

I saw `haxe`, I saw a foreign build chain, I didn't see package, I didn't see .d.ts, and I said "oh."

I looked in `haxe,` I saw something being transcompiled.

I tried installing, it wouldn't install.  

I didn't see any of the `npm` standard stuff, so I assumed `haxe` was doing something weird with its platform targetting stuff

I said "this might be a nice thing for `typescript` people."  I changed it

bummer if this is all wasted work

no, my stuff didn't pick your `.d.ts` up.  standard typescript setup, no funky anything, no plugins

**Comment by StoneCypher** [comment]
wonder if that's how the other typescript guy did this and ended up not on the list too

maybe add your own under `typescript` so people realize it's supposed to work?  i didn't even realize you had a typescript setup that was supposed to be here.  none of the standard files are in the standard locations

**Comment by boronine** [comment]
@StoneCypher the NPM packages (as well as website and other artifacts) are built using Nix. You can see the README in this repo for more info. For your purposes I don't think setting up Nix is necessary, this is just FYI.

Let's continue the TypeScript discussion is the new issue you created: https://github.com/hsluv/hsluv/issues/59
