### ISSUE TITLE
There are two Typescript implementations

### ISSUE THREAD

**Issue by StoneCypher** [hsluv/hsluv#59]
I wanted to update an older library of mine, [husl-harmony](https://github.com/StoneCypher/husl_harmony/), to the newer math, and newer tooling.

I went to look at your [implementations list](https://www.hsluv.org/implementations/) because the Haxe approach isn't convenient under Typescript, to see if there was a native typescript one.

There wasn't, so [I wrote one](https://github.com/StoneCypher/hsluv.ts), under the community standard `-ts` name.

In trying to publish the completed product, I learned that @gfmio already did, and [already published under the standard name](https://www.npmjs.com/package/hsluv-ts), but did not get it added to your site.

His and my implementation aren't actually the same, and both have advantages and disadvantages.

As a result I published mine as `@stonecypher/hsluv.ts` instead of `hsluv-ts`.

Please consider adding both the `hsluv-ts` and `@stonecypher/hsluv.ts` implementations to your list.  Thank you.

**Comment by boronine** [comment]
Bringing in discussion from #58, there's two TypeScript-related issues here.

1. Your report that TypeScript definitions in hsluv 0.1.0 don't work under your setup
2. Whether yours or @gfmio's implementation should be included in the list

Let's address #1 first. Could you provide some details of your setup? What editor/IDE you are using?

**Comment by boronine** [comment]
Just to avoid confusion, the package I am referring to is https://www.npmjs.com/package/hsluv/v/0.1.0

**Comment by StoneCypher** [comment]
> Bringing in discussion from #58, there's two TypeScript-related issues here.

I don't really want to do #1.  It's the result of a wacky non-standard setup

This post is asking you to please put the existing typescript implementations in the list - there are apparently three of them - because two people have now made their own, not recognizing that there's supposed to be one already

.

> Your report that TypeScript definitions in hsluv 0.1.0 don't work under your setup

I didn't make this report, and I'm not going to.  I haven't put in enough effort to figure out why the non-standard setup doesn't work.  

.

1. Whether yours or @gfmio's implementation should be included in the list

They absolutely both should be.

.

> Could you provide some details of your setup? What editor/IDE you are using?

That isn't relevant.  It's typescript that does the work.

1. Create a new project.
1. Install typescript.  `npx typescript --init`
1. Create `foo.ts`.  Import `hsluv`
1. Typescript can't see your `.d.ts`

Because Typescript can't see it, nothing else can either.  I tried in `vs code`, `sublime`, and `atom`, but if it doesn't work in the console and everything's pulling from the same config, that's your answer

I ran this against a github action.  Typescript can't see your thing under node 8, 12, or 13, under ubuntu, windows, or mac

I don't really want to debug a non-standard transcompiled setup where the configs aren't where they're supposed to be

Please list gfmio's implementation.  I think I'm not going to finish mine, despite the type system improvements, tooling, finished coverage, CI/CD, or extracted docs, but if I had known about his, I'd have used it.

**Comment by StoneCypher** [comment]
It also looks like your typescript implementation is just a `.d.ts` file for a minified es5 javascript that says "the inputs are `[number,number,number]` and the outputs are that or string"

This isn't really what a typescript user needs, and typescript can do a better job of inferring types without this `.d.ts`, as at least you'll get the inferential names of the functions and figure out which one you're supposed to be using

This also breaks ingres transcompilation, tree shaking, total packaging, module isolation, et cetera

A `.d.ts` file is just a way to cope with `es5 javascript` in typescript.  An actual typescript implementation is a very different thing.

**Comment by boronine** [comment]
1. I just tested hsluv@0.1.0 with VS Code and the editor *was* able to see the definitions, likewise for Intellij. The setup is `npm install hsluv`. You seem to be trying to build it from source? This is not necessary.
2. @gfmio's implementation simply provides a `.d.ts` file, so it is obsoleted by hsluv@0.1.0.

<img width="582" alt="hsluvtest" src="https://user-images.githubusercontent.com/93469/74751583-bd5b1f80-526d-11ea-81ab-9c54f73a034b.png">

**Comment by boronine** [comment]
Your implementation might have some value, but I don't enjoy your attitude so I'm closing this issue. You can reopen later if your attitude changes.

**Comment by StoneCypher** [comment]
> but I don't enjoy your attitude

sorry :(  i just wasted a bunch of work, and i'm sad

please help make sure the next person can get the ones that are already done

**Comment by StoneCypher** [comment]
gfmio's is great if you just don't want my involvement

i wasn't trying to be mean, i was just explaining why i didn't think they were the same thing, and why i didn't want to try to figure out the other one

i gave you reproduction steps to explain why yours doesn't work.  i don't know what else to do

i was trying to help.

**Comment by StoneCypher** [comment]
> The setup is npm install hsluv. You seem to be trying to build it from source?

no, same thing as you, just `--save-dev`

.

> I just tested hsluv@0.1.0 with VS Code and the editor was able to see the definitions

not on my windows machine, not on my work mac, and not on continuous integration in github actions on the nine-matrix stated

seems likely you have a global definition in node helping you out

.

at any rate, i don't actually understand how i offended you; i was just trying to offer information, and i'm kind of scared to offer other information in the fear of offending you further

.

> @gfmio's implementation simply provides a .d.ts file

oh.  i misunderstood what it was, then
