### ISSUE TITLE
Nix is broken on macOS Catalina

### ISSUE THREAD

**Issue by boronine** [hsluv/hsluv#61]
HSLuv uses Nix extensively to build the website as well as various packages. There exist some workarounds to get it to work on Catalina. We will wait for an official solution from the Nix project. If no solution is made we can consider using Docker or some other build system with better cross-platform support.

Discussion: https://github.com/NixOS/nix/issues/2925

Also noted by @roryokane here: https://github.com/hsluv/hsluv/pull/60

**Comment by roryokane** [comment]
The problem I described in #60 happened on macOS 10.14.6, which is Mojave, not Catalina.

**Comment by boronine** [comment]
Hallelujah! macOS support is back: https://nixos.org/nix/manual/#sect-macos-installation
