### ISSUE TITLE
New HSLuv logo? (with sketches)

### ISSUE THREAD

**Issue by hartwork** [hsluv/hsluv#62]
Hi!

The [current HSLuv logo](https://avatars3.githubusercontent.com/u/11480337?s=200&v=4) seems a bit too simple to me. I have played with some ideas on a candidate for a follow-up logo that I would like to share now. If none of these appeal to you, I won't be offended — it's just an idea.

### Icon size preview (32x32)
![hsluv_logo_32](https://user-images.githubusercontent.com/1577132/77916253-15d40280-7299-11ea-9992-6f451a82aac3.png)

### Source size preview (200x200, click to enlarge)
![hsluv_logo_200](https://user-images.githubusercontent.com/1577132/77916268-1a002000-7299-11ea-8517-af77211cf7f0.png)

The font is [Helvetica Neue](https://www.fontshop.com/families/neue-helvetica).

**Comment by hartwork** [comment]
Let me clarify that none of these sketches are final. They are meant to **start a discussion** so that we're on the same page with direction before going further. Unless you're sure you want to stick with logo 0.

**Comment by boronine** [comment]
I'm looking at the different use cases we have for a logo.

Favicons: not sure that tiny letters would work here, maybe some simple shape.
Avatars: the "logo" is generally next to the name, so letters are generally redundant. See:
https://www.npmjs.com/~hsluv
https://github.com/hsluv

Having said that in some places it is clear that some kind of logo would be nice:
https://pypi.org/user/hsluv/

Perhaps it would be more distinctive if instead of a square it would take the shape of CIELUV?

I want to keep this discussion open for a while to see if anyone else has ideas.

**Comment by hartwork** [comment]
> Favicons: not sure that tiny letters would work here, maybe some simple shape.

A favicon is 16x16. If we had `HSLuv` on a single line, with 5 letters we'd need at most 2 pixels width per character with a 1 pixel gap. That kills characters `H` and `U` (and potentially `v`).
So I guess in a favicon we would need to either just have letter `H` or break `HSLuv` up into to lines, at least. That would leave maximum 4x7 pixels per character.
Let me demo that: ![hsluv_16x16_single_line](https://user-images.githubusercontent.com/1577132/78992075-be585100-7b3a-11ea-966a-50a77408945d.png) ![hsluv_16x16_two_lines](https://user-images.githubusercontent.com/1577132/78992085-c1ebd800-7b3a-11ea-96c9-6e92106c15d0.png)


>  Avatars: the "logo" is generally next to the name, so letters are generally redundant. See:

Not in the list of organizations of a user on their GitHub profile page, e.g.:
![hsluv_orgs](https://user-images.githubusercontent.com/1577132/78990669-594f2c00-7b37-11ea-9814-17b8d6985056.png)

That's the very place that made me notice we have a problem with the current logo and try adding text in the first place.

**Comment by hartwork** [comment]
Ticket is two years old now, closing.
