### ISSUE TITLE
Stopgap solution for Nix on Catalina

### ISSUE THREAD

**Issue by boronine** [hsluv/hsluv#63]
For Mac users unfamiliar with Nix, our build system is unapproachable due to #61. We must make it possible for such a user to configure an HSLuv build quickly.

Ideas:
- See if we can use a workaround from https://github.com/NixOS/nix/issues/2925
- Wrap the build in a Dockerfile (bonus - Windows support)
- Vagrant? Something else?

Whatever the solution, it needs to be clearly explained in the README.

**Comment by hartwork** [comment]
+1 for Docker

**Comment by boronine** [comment]
I am inclined toward Docker as well, it's probably the quickest path to a successful build. I was looking into running Nix inside Docker, I think it can be done using something like:

```
FROM nixpkgs/nix:nixos-19.03
VOLUME /hsluv
VOLUME /nix
WORKDIR /hsluv
```

Nix philosophy doesn't really have a concept of "installation", instead all the files of all the dependencies are cached in `/nix`. If we can make this directory pluggable inside the Docker container we will avoid refetching of dependencies.

**Comment by boronine** [comment]
I believe this issue is the most important task for HSLuv as a project right now since it's blocking contributions from a huge pool of developers. When I get time to work on it I will notify this discussion, until then - PRs welcome!

**Comment by hartwork** [comment]
For the volume magic mentioned above, you might need docker-compose on top. Or an approach approach leveraging Docker layers and/or base images as a build cache.

**Comment by hartwork** [comment]
When I try with this `Dockerfile`…
```Dockerfile
FROM nixos/nix

RUN mkdir /tmp/build/
COPY default.nix  /tmp/build/
COPY javascript/  /tmp/build/javascript/
COPY haxe/        /tmp/build/haxe/
COPY snapshots/   /tmp/build/snapshots/
COPY website/     /tmp/build/website/

WORKDIR /tmp/build

RUN nix-build -A test
RUN nix-build -A website
```
but I get…
```console
# docker build .
[..]
building '/nix/store/gs9apgljn16n81r4zrkbgdzw320a98p1-hsluv-js-compile.drv'...
Invalid_argument("index out of bounds")
[..]
The command '/bin/sh -c nix-build -A test' returned a non-zero code: 100
```
Any ideas why?

I should mention that I don't have any nix background, yet.

**Comment by hartwork** [comment]
I found the origin of error `Invalid_argument("index out of bounds")` now, please see pull request #70 for a fix.

**Comment by hartwork** [comment]
Pull request #71 now has a docker integration for review.

**Comment by boronine** [comment]
I think we may have fixed this :) I just updated the README. Does the new `./run.sh` script work on your local?

**Comment by hartwork** [comment]
I had a quick look now: `run.sh` doesn't seem ready for local use with just a Git clone around, e.g.
- I don't have a file `secrets.txt` so sourcing will fail in line 7.
- `HSLUV_RUNTIME=docker` might be a good default. Environment Variable `HSLUV_RUNTIME` could also be made required, instead.

**Comment by boronine** [comment]
Nice catch about `secrets.txt`. Fixed here: https://github.com/hsluv/hsluv/commit/891edd6a46d6e5bd8d29749c209c76887e062a6e

I think I'd prefer keeping the current default for now since it's the native one. We can see later. 

I think that's it for this issue - we have a build solution for Mac with only Docker as a requirement. That's very convenient. Thank you for your contribution here!
