### ISSUE TITLE
HPLuv max values?

### ISSUE THREAD

**Issue by makeworld-the-better-one** [hsluv/hsluv#78]
It's my understanding that for the standard implementation, HSLuv ranges from `[0, 0, 0]` to `[360, 100, 100]`. I thought HPLuv would have the same range, but looking at `snapshot-rev4.json` I've seen the S value go over 490. The H and L values appear to have the same range as HSLuv.

Why is the HPLuv S value range so large? And what is the max value? I ask this so that I can scale to `[0..1]` for usage in a library.

**Comment by makeworld-the-better-one** [comment]
Alright after some searching with `less`, the highest HPLuv S value I found was a gigantic `1784.2359183569076`, for the color `#ffff00`. What gives?

**Comment by boronine** [comment]
These HPLuv values are indeed invalid, they are outside of HPLuv. They could probably be excluded from the snapshot. Note that HSLuv spans the entire sRGB gamut whereas HPLuv only contains a portion of it.

**Comment by makeworld-the-better-one** [comment]
So if I were to write code that converted the S and L values to `[0..1]`, then the max value of S would still be 360 for HPLuv? And it's just that sometimes invalid values could be generated?

**Comment by boronine** [comment]
Not sure exactly the scenario you're describing, but it is not safe to convert random RGB values to HPLuv, you might end up with an invalid value. You can clamp S to [0...100] range to mitigate that.

**Comment by makeworld-the-better-one** [comment]
I'm saying that instead of the valid S values being `[0..100]`, I'd like them to be `[0..1]`. Now that I know the max valid S value is 100, I can easily go about this by dividing by 100. Thanks!

**Comment by makeworld-the-better-one** [comment]
> They could probably be excluded from the snapshot

I think it's useful to have them there as an example, but it'd be nice if the valid range and the possibility of invalid output was noted somewhere.
