### ISSUE TITLE
Website's demo color picker breaks  on #ff0000 and #0000ff, and any color with exactly the same L* value

### ISSUE THREAD

**Issue by Tynach** [hsluv/hsluv#85]
Here's what it looks like for the color `#ff0000`, which has an L\* value of `53.2371155954294` (you don't have to type a precise L\* value to get the visual bug, but I did here to demonstrate a variation of the bug next):
![Screenshot_20220914_133530](https://user-images.githubusercontent.com/224197/190257089-41b8dd7b-079e-4dd2-b38b-0ffa5a29bc86.png)

It looks slightly worse if I make it just a bit more precise, with an L\* of 53.23711559542936:
![Screenshot_20220914_133827](https://user-images.githubusercontent.com/224197/190257604-d24fda5a-f4b1-40c7-ba37-21492e06e7fa.png)

And it looks abysmal if I plug in the color `#0000ff`, which has an L\* of `32.3008729039802` (I couldn't find any variations like the 'red squares' found by more precise versions of `#ff0000`'s L\* value; all values from 32.3...8017 through 32.3...8033 are identical):
![Screenshot_20220914_134242](https://user-images.githubusercontent.com/224197/190258384-d5d3134f-3494-448e-aba6-9415141a3120.png)

It's possible it breaks for L\* values other than `53.2371155954294` and `32.3008729039802` as well, but I can't find any.

I don't know when this started happening, but when I used the site like a year or two ago it *didn't* happen. I've tested on the Linux version of Firefox, as well as the Linux version of Chrome, and get the same results on both.

**Comment by boronine** [comment]
Thank you for the excellent bug report. I did make changes to the implementation recently and may have introduced a regression. Will investigate later today.

**Comment by boronine** [comment]
Thanks again @Tynach! The culrpit was this careless merge: https://github.com/hsluv/hsluv/commit/6d5e6e02812432093e298707bfa60e3d80ad242e

**Comment by Tynach** [comment]
> Thanks again @Tynach! The culrpit was this careless merge: [6d5e6e0](https://github.com/hsluv/hsluv/commit/6d5e6e02812432093e298707bfa60e3d80ad242e)

I'm not sure I see anything immediately wrong with that merge. Heck, I myself am all for higher precision values being used.. But I'm not entirely sure what `kappa` and `epsilon` are used for. Those look the most suspect to me, because the old values look truncated compared to the new ones, rather than rounded (if the new values are to be trusted).

**Comment by Tynach** [comment]
I'm not sure I see anything immediately wrong with that merge, @boronine. Heck, I myself am very much for higher precision values being used.. But I'm not entirely sure what `kappa` and `epsilon` are used for. Those look the most suspect to me, because the old values look truncated compared to the new ones, rather than rounded (if the new values are to be trusted).

**Comment by boronine** [comment]
The issue is that I use the same constants in the Maxima files (/math folder here), the output of which gets hardcoded back into the code: https://github.com/hsluv/hsluv-javascript/blob/main/src/hsluv.ts#L215-L237

So if we were updating them for higher precision I would have to also update the Maxima files to keep them in sync.

I don't think the precision here makes any difference, it's mostly for vanity. It all gets rounded out when number are finally converted to RGB for display.

**Comment by boronine** [comment]
kappa and epsilon are part of the LUV <-> XYZ formula:

https://github.com/hsluv/hsluv/blob/master/math/cie.mac#L52-L60

**Comment by boronine** [comment]
Actually looking back at the Maxima files most of the constants are derived from basic expressions, so actually I'm not sure where exactly it went out of sync...

**Comment by Tynach** [comment]
@boronine Ah, so Kappa is basically the slope of the linear section at the start (multiplied by 100 relative to what I use for the slope, as my functions assume both input and output to be in the 0.0 through 1.0 range, but L\* is typically given in a range between 0.0 and 100.0), and Epsilon is the value which I label `cutoffToGamma`.

If I were you, I would define them as:

```haxe
    private static var kappa:Float = 24389.0/27.0;
    private static var epsilon:Float = 216.0/24389.0;
```

Similarly with the other numbers, which I'd either have computed at compile time from basic constants like chromaticity coordinates, *or* define all the values as they are through fractions in a similar way.

The former is how I define them in my various shaders on Shadertoy, so that I can always swap around different sets of primaries and white points easily.
